;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-insert-opening
		autopair-insert-or-skip-quote
		autopair-newline
		autopair-skip-close-maybe
		awesome-pair-close-round
		awesome-pair-double-quote
		awesome-pair-equal
		awesome-pair-forward-delete
		awesome-pair-open-curly
		awesome-pair-open-round
		awesome-pair-space
		c-electric-semi&comma
		c-electric-slash
		electric-newline-and-maybe-indent
		ignore
		indent-for-tab-command
		kill-ring-save
		mwim-beginning
		mwim-end
		ns-open-file-using-panel
		org-delete-char
		org-force-self-insert
		org-hydra/self-insert-command-and-exit
		org-return
		org-self-insert-command
		org-yank
		upcase-dwim
		yank-rectangle
		))

(setq mc/cmds-to-run-once
      '(
		youdao-dictionary-search-at-point+
		gofmt
		))
