;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-insert-opening
		autopair-insert-or-skip-quote
		autopair-newline
		autopair-skip-close-maybe
		browse-kill-ring
		c-electric-semi&comma
		c-electric-slash
		dabbrev-completion
		electric-newline-and-maybe-indent
		end-of-buffer
		ignore
		indent-for-tab-command
		kill-ring-save
		lsp-signature-previous
		mouse-set-region
		mwim-beginning
		mwim-end
		treemacs-leftclick-action
		yank-rectangle
		))

(setq mc/cmds-to-run-once
      '(
		@-ask-inter-num
		beginning-of-buffer
		copy-rectangle-as-kill
		counsel-M-x
		counsel-find-file
		describe-key
		handle-switch-frame
		keyboard-escape-quit
		kill-region
		lsp-ui-doc--handle-mouse-movement
		move-past-close-and-reindent
		ns-copy-including-secondary
		))
